src/src/Entity/Record.php
<?php

namespace App\Entity;

use App\Repository\RecordRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecordRepository::class)
 */
class Record
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $releasedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Artist::class, inversedBy="records")
     * @ORM\JoinColumn(nullable=false)
     */
    private $artist;

    /**
     * @ORM\ManyToOne(targetEntity=Label::class, inversedBy="records")
     */
    private $label;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="record", orphanRemoval=true)
     */
    private $notes;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReleasedAt(): ?\DateTimeInterface
    {
        return $this->releasedAt;
    }

    public function setReleasedAt(\DateTimeInterface $releasedAt): self
    {
        $this->releasedAt = $releasedAt;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getLabel(): ?Label
    {
        return $this->label;
    }

    public function setLabel(?Label $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setRecord($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getRecord() === $this) {
                $note->setRecord(null);
            }
        }

        return $this;
    }

    /**
     * Note moyenne
     */
    public function getAverageNote(): ?float
    {
        if($this->notes->count() === 0)
            return null;

        $notes = $this->notes
            ->map(fn(Note $note) => $note->getValue())
            ->toArray();

        $total = array_sum($notes);

        return $total/$this->notes->count();
    }
}

src/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cette adresse est déjà utilisée.")
 * @UniqueEntity(fields={"pseudo"}, message="Ce pseudo est déjà pris.")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $pseudo;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="author", orphanRemoval=true)
     */
    private $notes;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setAuthor($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getAuthor() === $this) {
                $note->setAuthor(null);
            }
        }

        return $this;
    }
}

src/src/Controller/RecordController.php
<?php

namespace App\Controller;

use App\Entity\Artist;
use App\Entity\Label;
use App\Entity\Note;
use App\Entity\Record;
use App\Form\NoteFormType;
use App\Repository\ArtistRepository;
use App\Repository\NoteRepository;
use App\Repository\RecordRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class RecordController extends AbstractController
{
    /**
     * @Route("/artiste-list", name="artiste_list")
     */
    public function index(ArtistRepository $repository)
    {
       return $this->render('record/artist_list.html.twig', [
           "artist_list" => $repository->findAll(),
       ]);
    }

    /**
     * @Route("/artiste/{id}", name="artiste_page")
     */
    public function artistPage(Artist $artist)
    {
        return $this->render('record/artist_page.html.twig', [
            'artist' => $artist,
        ]);
    }

    /**
     * @Route("/label/{id}", name="label_page")
     */
    public function labelPage(Label $label)
    {
        return $this->render('record/label_page.html.twig', [
            'label' => $label,
        ]);
    }

    /**
     * @Route("/record/{id}", name="record_page")
     */
    public function recordPage(
        Record $record,
        NoteRepository $repository,
        Request $request,
        EntityManagerInterface $manager
    ){
        //Recherche d'une note existante
        if(null !== $this->getUser()){
            $note = $repository->findOneBy([
               'author' => $this->getUser(),
               'record' => $record
            ]);
        }

        //Si la note n'existe pas on en crée une nouvelle
        $note ??= (new Note())
            ->setAuthor($this->getUser())
            ->setRecord($record);

        //Création du formulaire
        $form = $this->createForm(NoteFormType::class, $note);
        $form->handleRequest($request);

        if($this->getUser() !== null && $form->isSubmitted() && $form->isValid()) {
            $manager->persist($note);
            $manager->flush();

            $this->addFlash('success', 'Votre note a été enregistrée.');
        }


        return $this->render('record/record_page.html.twig', [
            'record' => $record,
            'note_form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/news", name="record_news")
     */
    public function recordNews(RecordRepository $repository)
    {
        return $this->render('record/record_news.html.twig', [
            'record_news' => $repository->getNews(),
        ]);
    }

    /**
     * @Route("/note/{id}/delete/{token}", name="record_note_delete")
     * @IsGranted("NOTE_DELETE", subject="note")
     */
    public function deleteRecordNote(Note $note, string $token, EntityManagerInterface $manager)
    {
        //Vérification du jeton CSRF
        if(false === $this->isCsrfTokenValid('record_note_delete', $token)) {
            $this->addFlash('Warning', 'Jeton invalide.');
            return $this->redirectToRoute('record_page', ['id' => $note->getRecord()->getId()]);
        }

        //Remove note
        $manager->remove($note);
        $manager->flush();
        $this->addFlash('info', 'Votre note a bien été supprimée.');
        return $this->redirectToRoute('record_page', ['id' => $note->getRecord()->getId()]);
    }

}

src/templates/record/_record_list.html.twig
{% for record in record_list %}
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-128x128">
                    <img src="https://loremflickr.com/256/256/album,music/all?lock={{ record.id }}" alt="Image">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <span class="tag is-primary">
                            {{ record.averageNote is null ? '?' : record.averageNote|number_format(2, '.') }}
                            /10
                        </span>
                        <a href="{{ path('record_page', {id: record.id}) }}" class="has-text-primary">
                            <strong>{{ record.title }}</strong>
                        </a>
                        <small>{{ record.releasedAt|date('d/m/y') }}</small>
                        <br>
                        <small>
                            <strong>Artiste:</strong>
                            <a href="{{ path('artiste_page', {id: record.artist.id}) }}">
                                {{ record.artist.name }}
                            </a>
                        </small><br>
                        {% if record.label is not null %}
                            <small>
                                <strong>Label :</strong>
                                <a href="{{path('label_page', {id: record.label.id}) }}">{{  record.label.name }}</a>
                            </small><br>
                        {% endif %}
                        {{ record.description }}
                    </p>
                </div>
            </div>
        </article>
    </div>
{% endfor %}

src/templates/record/artist_list.html.twig
{% extends "_template.html.twig" %}

{% block title %}
    Artistes: {{ artist_list|length }}
{% endblock %}

{% block content %}
    <div class="columns is-multiline">
        {% for artist in artist_list %}
            <div class="column is-one-third">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-128x128">
                                <img src="https://loremflickr.com/256/256/artist,music,musician/all?lock={{ artist.id }}" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <a href="{{ path('artiste_page', {id:artist.id}) }}" class="has-text-primary">
                                        <strong>{{ artist.name }}</strong>
                                    </a>
                                    <br>
                                    <small>
                                        <strong>Albums:</strong>
                                        {{ artist.records|length }}
                                    </small><br>
                                    {{ artist.description|ellipsis(100) }}
                                </p>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/templates/record/artist_page.html.twig
{% extends '_template.html.twig' %}

{% block title %}
    Artiste: {{ artist.name }}
{% endblock %}

{% block content %}
    <div class="content">
        <p>
            {{ artist.description }}
        </p>
    </div>

    <h2 class="subtitle">
        Discographie: {{ artist.records|length }}
    </h2>

    {% include 'record/_record_list.html.twig' with {
        record_list: artist.records
    } %}

{% endblock %}

src/templates/record/label_page.html.twig
{% extends '_template.html.twig' %}

{% block title %}
    Label: {{ label.name }}
{% endblock %}

{% block content %}
    <h2 class="subtitle">
        Production: {{ label.records|length }}
    </h2>

    {% include 'record/_record_list.html.twig' with {
        record_list: label.records
    } %}

{% endblock %}

src/templates/record/record_news.html.twig
{% extends "_template.html.twig" %}

{% block title %}
    Nouveauté : {{ record_news|length }}
{% endblock %}

{% block content %}
    {% include 'record/_record_list.html.twig' with {
        record_list: record_news
    } %}
{% endblock %}

src/templates/record/record_page.html.twig
{% extends '_template.html.twig' %}

{% block title %}
    {{ record.title }}
{% endblock %}

{% block content %}
    <div class="columns">
        <div class="column is-two-fifth">
            <figure class="image is-1by1">
                <img src="https://loremflickr.com/1024/1024/album,music/all?lock={{ record.id }}">
            </figure>
        </div>

        <div class="column">
            <h2 class="subtitle is-size-3">
                Artiste:
                <a href="{{ path('artiste_page', {id:record.artist.id}) }}">
                    {{ record.artist.name }}
                </a>
            </h2>

            {%  if record.label is not null %}
                <h3 class="subtitle is-size-3">
                    Label:
                    <a href="{{ path('label_page', {id: record.label.id}) }}">
                        {{ record.label.name }}
                    </a>
                </h3>
            {%  endif %}

            <p class="content">
                {{ record.description }}
            </p>

            <hr>

            <h6 class="is-size-7">
                 <span class="tag is-primary">
                    {{ record.averageNote is null ? '?' : record.averageNote|number_format(2, '.') }}
                    /10
                </span>
                <span class="icon has-text-info"><i class="fas fa-info-circle"></i></span>
                <span>Sorti le {{ record.releasedAt|date('d/m/y') }}</span>
            </h6>
            <hr>
            {% if is_granted('ROLE_USER') %}
                {{ form_start(note_form) }}
                    {{ form_row(note_form.value, {
                        label: 'Votre note:',
                        help: 'Vous ne pouvez noter un album qu\'une seule fois.'
                    }) }}

                {{ form_row(note_form.comment, {
                    label: 'Commentaire (facultatif):'
                }) }}

                <button type="submit" class="button is-fullwidth is-primary">
                    Noter !
                </button>

                {{ form_end(note_form) }}
            {% else %}
                <div class="section">
                    <div class="content">
                        <p class="has-text-centered">Connectes toi pour noter !</p>
                    </div>
                    <div class="columns is-centered">
                        <div class="column is-one-quarter">
                            <a href="{{ path('app_register') }}" class="button is-fullwidth is-info is-outlined">Inscription</a>
                        </div>
                        <div class="column is-one-quarter">
                            <a href="{{ path('app_login') }}" class="button is-fullwidth is-primary">Connexion</a>
                        </div>
                    </div>
                </div>
            {% endif %}

        </div>
    </div>

    {% for note in record.notes %}
        <article class="media">
            <figure class="media-left">
                <p class="image is-64x64">
                    <img src="https://robohash.org/{{ note.author.username }}?set=set5" alt="Avatar">
                </p>
            </figure>

            <div class="media-content">
                <div class="content">
                    <p>
                        <span class="tag is-primary is-light">
                            {{ note.value }}
                            /10
                        </span>
                        <strong>{{ note.author.pseudo }}</strong>
                        <br>
                        {{ note.comment }}
                    </p>
                </div>
            </div>

            {% if is_granted('NOTE_DELETE', note) %}
                <div class="media-right">
                    <a href="{{ path('record_note_delete', {
                                id:note.id,
                                token: csrf_token('record_note_delete')
                            }) }}" class="button is-small is-danger is-light">
                        <i class="fas fa-times"></i>
                    </a>
                </div>
            {% endif %}
        </article>
    {% endfor %}
{% endblock %}